name: build java
on:
  push:
    branches:
      - main
    paths:
      - "go1.17-redis/**"
jobs:
  push:
    name: "go1.17-redis"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - go1.17-redis
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./go1.17-redis
          file: ./go1.17-redis/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mccbena/go1.17-redis