name: build java
on:
  push:
    branches:
      - main
    paths:
      - "json-c-java17/**"
jobs:
  push:
    name: "json-c-java17"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - json-c-java17
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./json-c-java17
          file: ./json-c-java17/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/mccbena/json-c-java17